[package]
name = "monotree"
version = "0.1.0"
authors = ["Francis <thyeem@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
hex = "0.4.1"
blake2-rfc = "0.2.18"
const-utils = "0.1.1"
num = "0.2.1"
rocksdb = "0.13.0"
hashbrown = "0.7"
criterion = "0.3"
starling = "3.1.3"
starminer = {path="./starminer"}
serde = "1.0.104"
bincode = "1.2.1"

[[bench]]
name = "benchmark"
harness = false