[package]
name = "monotree"
version = "0.1.0"
authors = ["Francis <thyeem@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
hex = "0.4.1"
blake2-rfc = "0.2.18"
rocksdb = "0.13.0"
num = "0.2.1"
hashbrown = "0.7"
const-utils = "0.1.1"
scopeguard = "1.1.0"
paste = "0.1.7"
criterion = "0.3"


[[bench]]
name = "benchmark"
harness = false